# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='number')),
            ],
            options={
                'db_table': 'test',
                'verbose_name': 'Test',
                'verbose_name_plural': 'Test',
            },
        ),
    ]
