# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('email_sender', models.CharField(max_length=64, verbose_name='\u53d1\u9001\u8005')),
                ('email_receiver', models.CharField(max_length=64, verbose_name='\u63a5\u53d7\u8005')),
                ('email_title', models.CharField(max_length=256, verbose_name='\u90ae\u4ef6\u4e3b\u9898')),
                ('email_content', models.TextField(verbose_name='\u90ae\u4ef6\u5185\u5bb9')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='\u90ae\u4ef6\u53d1\u9001\u65f6\u95f4')),
                ('email_status', models.IntegerField(choices=[(0, '\u672a\u8bfb'), (1, '\u5df2\u8bfb'), (-1, '\u5220\u9664')], default=0)),
            ],
            options={
                'db_table': 'email',
                'verbose_name': '\u90ae\u4ef6\u8868',
                'verbose_name_plural': '\u90ae\u4ef6\u8868',
            },
        ),
    ]
