# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('user_number', models.CharField(max_length=10, unique=True, verbose_name='\u7f16\u53f7')),
                ('user_name', models.CharField(max_length=64, unique=True, verbose_name='\u59d3\u540d')),
                ('user_sex', models.BooleanField(default=True, verbose_name='\u6027\u522b')),
                ('user_birthday', models.DateTimeField(verbose_name='\u51fa\u751f\u65e5\u671f')),
                ('user_email', models.CharField(max_length=64, verbose_name='\u90ae\u7bb1')),
                ('user_phone', models.CharField(max_length=11, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('user_address', models.CharField(default=0, max_length=256, verbose_name='\u5bb6\u5ead\u4f4f\u5740')),
                ('user_role', models.IntegerField(choices=[(0, 'customer'), (1, 'manager')], default=0, verbose_name='\u7528\u6237\u89d2\u8272\u7c7b\u578b')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='\u6ce8\u518c\u65f6\u95f4')),
                ('user_status', models.IntegerField(choices=[(0, '\u6b63\u5e38\u72b6\u6001'), (-1, '\u7981\u7528\u72b6\u6001'), (-2, '\u8fc7\u671f')], default=0, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'user',
                'verbose_name': '\u7528\u6237\u8868',
                'verbose_name_plural': '\u7528\u6237\u8868',
            },
        ),
    ]
