# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=64, verbose_name='\u59d3\u540d'),
        ),
    ]
