# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20170505_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=256, null=True, verbose_name='\u7528\u6237\u5bc6\u7801'),
        ),
    ]
